defmodule CrucibleFramework.Persistence.ArtifactRecord do
  @moduledoc """
  Ecto schema for persisted artifacts generated by runs.
  """

  use Ecto.Schema
  import Ecto.Changeset

  alias CrucibleFramework.Persistence.RunRecord

  @primary_key {:id, :binary_id, autogenerate: true}
  schema "artifacts" do
    belongs_to(:run, RunRecord, type: :binary_id)

    field(:name, :string)
    field(:type, :string)
    field(:location, :string)
    field(:format, :string)
    field(:metadata, :map, default: %{})

    timestamps(type: :utc_datetime)
  end

  def changeset(schema, attrs) do
    schema
    |> cast(attrs, [:run_id, :name, :type, :location, :format, :metadata])
    |> validate_required([:run_id, :name, :type])
    |> foreign_key_constraint(:run_id)
  end
end
